// AUTO-GENERATED by scripts/generate-routes.mjs — do not edit by hand.
// Regenerated on every build (npm run build) and by `npm run routes`.
// Static, file-based pages discovered under src/app. Database-backed pages
// are fetched at request time instead, so they are not listed here.

export const STATIC_ROUTES = [
  "/blogs",
] as const;
