// Scans the App Router for real, indexable, file-based pages and writes the
// result to src/lib/generated-routes.ts.
//
// Most of the site lives in the database (see /pages/public), and those pages
// reach the sitemap at request time. But a route added straight to the
// codebase — src/app/(site)/pricing/page.tsx — has no database row, so
// nothing would ever list it. This script closes that gap: it runs from the
// "prebuild" hook, so every build rediscovers the current set of routes and no
// one has to remember to update a list by hand.
import { readdirSync, writeFileSync, readFileSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const APP_DIR = join(ROOT, "src", "app");
const OUT_FILE = join(ROOT, "src", "lib", "generated-routes.ts");

// Segments that must never reach the sitemap.
const SKIP_DIRS = new Set(["(admin)", "admin", "_components", "api"]);

const isRouteGroup = (name) => name.startsWith("(") && name.endsWith(")");
const isDynamic = (name) => name.includes("[");
// Metadata/handler folders like "og-image" or "llms.txt" — not real pages.
const isPrivate = (name) => name.startsWith("_") || name.startsWith(".");

/** Walk src/app collecting the URL path of every static page.tsx. */
function collect(dir, segments = [], found = []) {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return found;
  }

  const hasPage = entries.some(
    (e) => e.isFile() && /^page\.(tsx|ts|jsx|js)$/.test(e.name),
  );
  if (hasPage && segments.length > 0) {
    found.push("/" + segments.join("/"));
  }

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const { name } = entry;
    if (SKIP_DIRS.has(name) || isPrivate(name) || isDynamic(name)) continue;
    // Route groups shape the folder tree but not the URL, so they add no segment.
    const next = isRouteGroup(name) ? segments : [...segments, name];
    collect(join(dir, name), next, found);
  }
  return found;
}

const routes = [...new Set(collect(APP_DIR))].sort();

const banner = `// AUTO-GENERATED by scripts/generate-routes.mjs — do not edit by hand.
// Regenerated on every build (npm run build) and by \`npm run routes\`.
// Static, file-based pages discovered under src/app. Database-backed pages
// are fetched at request time instead, so they are not listed here.

`;

const body =
  routes.length > 0
    ? `export const STATIC_ROUTES = [\n${routes.map((r) => `  "${r}",`).join("\n")}\n] as const;\n`
    : `export const STATIC_ROUTES = [] as const;\n`;

const next = banner + body;

// Only write when something changed, so builds don't churn the file's mtime.
let current = "";
try {
  current = readFileSync(OUT_FILE, "utf8");
} catch {
  /* first run */
}
if (current !== next) {
  writeFileSync(OUT_FILE, next);
  console.log(
    `[routes] wrote ${relative(ROOT, OUT_FILE)} (${routes.length} static route${routes.length === 1 ? "" : "s"})`,
  );
} else {
  console.log(`[routes] up to date (${routes.length} static)`);
}
